# Generated by Django 5.2.3 on 2025-06-26 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='E-mail inválido.')], verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\) \\d{4,5}-\\d{4}$', 'Formato inválido. Use: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX.')], verbose_name='Telefone')),
                ('telefone_secundario', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\) \\d{4,5}-\\d{4}$', 'Formato inválido. Use: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX.')], verbose_name='Telefone Secundário')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
